---
title: "Preprocessing"
author: "Admin"
date: "24 4 2019"
output:
  html_document:
    df_print: paged
params:
  data:
  target: "Species"
  type: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("summarytools")
require("tpotr")
require("mlr")
require("lime")
```

## Raw Dataset

```{r results='asis', echo=FALSE}
data <- data
print(dfSummary(data, plain.ascii = FALSE, style = "grid", graph.magnif = 0.75, tmp.img.dir = "/tmp"))
```

## Fitting a machine learning pipeline
```{r echo=FALSE}
learner <- makeLearner(cl = "classif.tpot", predict.type = "prob", 
                       population_size = 10, generations = 15, 
                       verbosity = 2)
if(type=="classif"){
  task <- makeClassifTask(data = data, target = target)
} else{
  task <- makeRegrTask(data = data, target = target)
}
mod <- train(learner, task = task)
# print(paste("The fitted pipeline is: " , printPipeline(mod)))
predict(obj = mod, newdata = iris[37:43,])
```

## Explaining the pipeline model
```{r echo=FALSE}
explainer = lime(iris, mod)
explanation = explain(iris[37:43,], explainer, n_labels = 1, n_features = 4)
plot_features(explanation)

```
